### ISSUE TITLE
Updated past tasks

### ISSUE THREAD

**Issue by russc** [williampansky/skynet.override#1]
The regular skynet has an icon on past tasks that have been updated.  This version could use something like that, but ideally, something A LOT more noticeable.
![screen shot 2018-02-19 at 8 15 59 am](https://user-images.githubusercontent.com/738104/36382075-5c69e936-154d-11e8-907e-45862441682e.png)

**Comment by williampansky** [comment]
Roger that! Any ideas on how it should be implemented? Similar "label" style? Or maybe something else?

**Comment by russc** [comment]
Similar label would be a start. It would be cool if you saw something in your current day's list that drew your attention to it too.

**Comment by williampansky** [comment]
So, for now, I've implemented a variant on the original labels. The challenge was avoiding disruption with the table alignment via it's inner elements. Should work, for now! :)
